spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}${DATASOURCE_DBNAME}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  sql:
    init:
      mode: always

server:
  shutdown: graceful
  port: ${SERVER_PORT}

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: false
    database:
      type: in-memory
